source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'iOS_Chart_Sample' do
   pod 'Charts', '~> 3.1.1'
   pod 'Alamofire'
   pod 'SwiftyJSON'
   pod 'SnapKit'
end
